{{
    config(
        cluster_by=['id'],
        alias='organisation',
        transient=false,
        tags=['stable']
    )
}}

SELECT
    lds_source_record_id,
    id,
    organisation_code,
    organisation_code_assinging_authority,
    name,
    description,
    location_type_source_concept_id,
    postcode,
    parent_organisation_id,
    open_date,
    close_date,
    is_obsolete,
    publisher_organisation_code,
    lds_source_record_shard_id,
    lds_id,
    lds_business_key,
    lds_source_dataset_id,
    lds_cdm_event_id,
    lds_versioner_event_id,
    lds_datetime_first_acquired,
    lds_datetime_update_acquired,
    lds_is_deleted,
    lds_start_datetime,
    lds_lakehouse_date_processed,
    lds_lakehouse_datetime_updated
FROM {{ ref('synapse_base_olids_organisation') }}
