{{
    config(
        cluster_by=['id'],
        alias='schedule',
        transient=false,
        tags=['stable']
    )
}}

SELECT
    lds_source_record_id,
    id,
    location_id,
    location_name,
    practitioner_id,
    publisher_organisation_id,
    start_date,
    end_date,
    type,
    name,
    is_private,
    publisher_organisation_code,
    lds_source_record_shard_id,
    lds_id,
    lds_business_key,
    lds_source_dataset_id,
    lds_cdm_event_id,
    lds_versioner_event_id,
    lds_datetime_first_acquired,
    lds_datetime_update_acquired,
    lds_is_deleted,
    lds_start_datetime,
    lds_lakehouse_date_processed,
    lds_lakehouse_datetime_updated
FROM {{ ref('synapse_base_olids_schedule') }}
