{{
    config(
        cluster_by=['procedure_request_source_concept_id', 'clinical_effective_date'],
        alias='procedure_request',
        transient=false,
        tags=['stable']
    )
}}

SELECT
    lds_source_record_id,
    id,
    person_id,
    patient_id,
    encounter_id,
    practitioner_id,
    clinical_effective_date,
    clinical_effective_date_precision_source_concept_id,
    date_recorded,
    description,
    procedure_request_source_concept_id,
    status_source_concept_id,
    age_at_event,
    age_at_event_baby,
    age_at_event_neonate,
    is_confidential,
    provider_organisation_id,
    publisher_organisation_id,
    author_organisation_id,
    publisher_organisation_code,
    patient_shard_id,
    person_shard_id,
    lds_source_record_shard_id,
    lds_id,
    lds_business_key,
    lds_source_dataset_id,
    lds_cdm_event_id,
    lds_versioner_event_id,
    lds_datetime_first_acquired,
    lds_datetime_update_acquired,
    lds_is_deleted,
    lds_start_datetime,
    lds_lakehouse_date_processed,
    lds_lakehouse_datetime_updated
FROM {{ ref('synapse_base_olids_procedure_request') }}
