version: 2
models:
  - name: landing_allergy_intolerance
    description: Landing cache for ALLERGY_INTOLERANCE.

  - name: landing_appointment
    description: Landing cache for APPOINTMENT.
    tests:
      - min_row_count:
          arguments:
            min_rows: 8000000
          config:
            severity: error
      - elementary.volume_anomalies:
          arguments:
            anomaly_direction: drop
          config:
            severity: warn
      - elementary.dimension_anomalies:
          arguments:
            dimensions:
              - publisher_organisation_code
          config:
            severity: warn

  - name: landing_appointment_practitioner
    description: Landing cache for APPOINTMENT_PRACTITIONER.

  - name: landing_concept
    description: Landing cache for CONCEPT.

  - name: landing_concept_map
    description: Landing cache for CONCEPT_MAP.

  - name: landing_diagnostic_order
    description: Landing cache for DIAGNOSTIC_ORDER.

  - name: landing_emis_clinical_code
    description: Landing cache for EMIS_CLINICAL_CODE.

  - name: landing_emis_drug_code
    description: Landing cache for EMIS_DRUG_CODE.

  - name: landing_encounter
    description: Landing cache for ENCOUNTER.
    tests:
      - min_row_count:
          arguments:
            min_rows: 50000000
          config:
            severity: error
      - elementary.volume_anomalies:
          arguments:
            anomaly_direction: drop
          config:
            severity: warn
      - elementary.dimension_anomalies:
          arguments:
            dimensions:
              - publisher_organisation_code
          config:
            severity: warn

  - name: landing_episode_of_care
    description: Landing cache for EPISODE_OF_CARE.
    tests:
      - min_row_count:
          arguments:
            min_rows: 300000
          config:
            severity: error
      - elementary.volume_anomalies:
          arguments:
            anomaly_direction: drop
          config:
            severity: warn
      - elementary.dimension_anomalies:
          arguments:
            dimensions:
              - publisher_organisation_code
          config:
            severity: warn

  - name: landing_location
    description: Landing cache for LOCATION.

  - name: landing_medication_order
    description: Landing cache for MEDICATION_ORDER.
    tests:
      - min_row_count:
          arguments:
            min_rows: 40000000
          config:
            severity: error
      - elementary.volume_anomalies:
          arguments:
            anomaly_direction: drop
          config:
            severity: warn
      - elementary.dimension_anomalies:
          arguments:
            dimensions:
              - publisher_organisation_code
          config:
            severity: warn

  - name: landing_medication_statement
    description: Landing cache for MEDICATION_STATEMENT.
    tests:
      - elementary.volume_anomalies:
          arguments:
            anomaly_direction: drop
          config:
            severity: warn
      - elementary.dimension_anomalies:
          arguments:
            dimensions:
              - publisher_organisation_code
          config:
            severity: warn

  - name: landing_national_data_opt_out
    description: Landing cache for NATIONAL_DATA_OPT_OUT.

  - name: landing_observation
    description: Landing cache for OBSERVATION.
    tests:
      - min_row_count:
          arguments:
            min_rows: 150000000
          config:
            severity: error
      - elementary.volume_anomalies:
          arguments:
            anomaly_direction: drop
          config:
            severity: warn
      - elementary.dimension_anomalies:
          arguments:
            dimensions:
              - publisher_organisation_code
          config:
            severity: warn

  - name: landing_organisation
    description: Landing cache for ORGANISATION.

  - name: landing_patient
    description: Landing cache for PATIENT.
    tests:
      - min_row_count:
          arguments:
            min_rows: 250000
          config:
            severity: error
      - elementary.volume_anomalies:
          arguments:
            anomaly_direction: drop
          config:
            severity: warn
      - elementary.dimension_anomalies:
          arguments:
            dimensions:
              - publisher_organisation_code
          config:
            severity: warn

  - name: landing_patient_address
    description: Landing cache for PATIENT_ADDRESS.

  - name: landing_patient_contact
    description: Landing cache for PATIENT_CONTACT.

  - name: landing_patient_person
    description: Landing cache for PATIENT_PERSON.
    tests:
      - min_row_count:
          arguments:
            min_rows: 200000
          config:
            severity: error

  - name: landing_patient_uprn
    description: Landing cache for PATIENT_UPRN.

  - name: landing_person
    description: Landing cache for PERSON.
    tests:
      - min_row_count:
          arguments:
            min_rows: 1500000
          config:
            severity: error

  - name: landing_postcode_hash
    description: Landing cache for POSTCODE_HASH.

  - name: landing_practitioner
    description: Landing cache for PRACTITIONER.

  - name: landing_practitioner_in_role
    description: Landing cache for PRACTITIONER_IN_ROLE.

  - name: landing_procedure_request
    description: Landing cache for PROCEDURE_REQUEST.

  - name: landing_referral_request
    description: Landing cache for REFERRAL_REQUEST.
    tests:
      - elementary.volume_anomalies:
          arguments:
            anomaly_direction: drop
          config:
            severity: warn
      - elementary.dimension_anomalies:
          arguments:
            dimensions:
              - publisher_organisation_code
          config:
            severity: warn

  - name: landing_schedule
    description: Landing cache for SCHEDULE.

  - name: landing_schedule_practitioner
    description: Landing cache for SCHEDULE_PRACTITIONER.
