{{
    config(
        materialized='incremental',
        unique_key='id',
        on_schema_change='fail',
        cluster_by=['bnf_chapter', 'mapped_concept_code', 'clinical_effective_date'],
        alias='medication_order',
        incremental_strategy='merge',
        transient=false,
        tags=['stable', 'incremental']
    )
}}

select
    lds_source_record_id,
    id,
    provider_organisation_id,
    person_id,
    patient_id,
    medication_statement_id,
    encounter_id,
    practitioner_id,
    observation_id,
    allergy_intolerance_id,
    diagnostic_order_id,
    referral_request_id,
    clinical_effective_date,
    clinical_effective_date_precision_source_concept_id,
    date_precision_source_code,
    date_precision_source_display,
    date_precision_code,
    date_precision_display,
    dose,
    quantity_value,
    quantity_value_description,
    quantity_unit,
    duration_days,
    estimated_cost,
    medication_name,
    medication_order_source_concept_id,
    medication_statement_source_concept_id,
    statement_medication_name,
    mapped_concept_id,
    mapped_concept_code,
    mapped_concept_display,
    source_code,
    source_display,
    source_system,
    target_system,
    bnf_chapter,
    bnf_section,
    bnf_code,
    bnf_name,
    bnf_reference,
    age_at_event,
    age_at_event_baby,
    age_at_event_neonate,
    issue_method,
    date_recorded,
    is_confidential,
    issue_method_description,
    publisher_organisation_id,
    author_organisation_id,
    publisher_organisation_code,
    patient_shard_id,
    person_shard_id,
    lds_source_record_shard_id,
    lds_id,
    lds_business_key,
    lds_source_dataset_id,
    lds_cdm_event_id,
    lds_versioner_event_id,
    lds_datetime_first_acquired,
    lds_datetime_update_acquired,
    lds_is_deleted,
    lds_start_datetime,
    lds_lakehouse_date_processed,
    lds_lakehouse_datetime_updated
from {{ ref('base_olids_medication_order') }}

{% if is_incremental() %}
    where lds_start_datetime > (select max(lds_start_datetime) from {{ this }})
{% endif %}
