{{
    config(
        cluster_by=['id'],
        transient=false,
        alias='person'
    )
}}

SELECT
    id,
    person_uuid,
    lds_source_record_id,
    req_nhs_number,
    matched_nhs_no,
    gender,
    date_of_birth,
    date_of_birth_year,
    date_of_birth_month,
    date_of_birth_precision,
    date_of_death,
    date_of_death_year,
    date_of_death_month,
    date_of_death_precision,
    death_notification_status,
    postcode,
    preferred_contact_method,
    nominated_pharmacy,
    dispensing_doctor,
    medical_appliance_supplier,
    gp_practice_code,
    gp_registration_date,
    nhais_posting_id,
    is_patient_flagged_sensitive,
    is_latest_for_person,
    error_success_code,
    lds_is_deleted,
    clinical_system,
    source_extraction_date,
    lds_transform_datetime
FROM {{ ref('conformed_person') }}
