{{
    config(
        cluster_by=['clinical_effective_date'],
        transient=false,
        alias='procedure_request'
    )
}}

SELECT
    id,
    lds_source_record_id,
    patient_id,
    person_id,
    publisher_organisation_id,
    provider_organisation_id,
    author_organisation_id,
    practitioner_id,
    encounter_id,
    clinical_effective_date,
    clinical_effective_date_precision_source_concept_id,
    date_precision_source_code,
    date_precision_source_display,
    date_precision_code,
    date_precision_display,
    date_recorded,
    description,
    procedure_request_source_concept_id,
    source_code,
    source_display,
    source_system,
    mapped_concept_id,
    mapped_concept_code,
    mapped_concept_display,
    target_system,
    age_at_event,
    age_at_event_baby,
    age_at_event_neonate,
    is_confidential,
    status_source_concept_id,
    status_source_code,
    status_source_display,
    status_code,
    status_display,
    lds_is_deleted,
    publisher_organisation_code,
    source_extraction_date,
    lds_transform_datetime
FROM {{ ref('conformed_procedure_request') }}
