{{
    config(
        materialized='incremental',
        unique_key='id',
        on_schema_change='fail',
        cluster_by=['medication_order_source_concept_id', 'clinical_effective_date'],
        alias='medication_order',
        incremental_strategy='merge',
        transient=false,
        tags=['stable', 'incremental']
    )
}}

select
    lds_record_id,
    id,
    organisation_id,
    person_id,
    patient_id,
    medication_statement_id,
    encounter_id,
    practitioner_id,
    observation_id,
    allergy_intolerance_id,
    diagnostic_order_id,
    referral_request_id,
    clinical_effective_date,
    date_precision_concept_id,
    date_precision_source_code,
    date_precision_source_display,
    date_precision_code,
    date_precision_display,
    dose,
    quantity_value,
    quantity_unit,
    duration_days,
    estimated_cost,
    medication_name,
    medication_order_source_concept_id,
    bnf_reference,
    age_at_event,
    age_at_event_baby,
    age_at_event_neonate,
    issue_method,
    date_recorded,
    is_confidential,
    issue_method_description,
    lds_id,
    lds_business_key,
    lds_dataset_id,
    lds_cdm_event_id,
    lds_versioner_event_id,
    record_owner_organisation_code,
    lds_datetime_data_acquired,
    lds_initial_data_received_date,
    lds_is_deleted,
    lds_start_date_time,
    lds_lakehouse_date_processed,
    lds_lakehouse_datetime_updated,
    medication_statement_source_concept_id,
    statement_medication_name,
    mapped_concept_id,
    mapped_concept_code,
    mapped_concept_display,
    source_code,
    source_display,
    source_system,
    target_system
from {{ ref('base_olids_medication_order') }}

{% if is_incremental() %}
    where lds_start_date_time > (select max(lds_start_date_time) from {{ this }})
{% endif %}