{{
    config(
        materialized='incremental',
        unique_key='id',
        on_schema_change='fail',
        cluster_by=['start_date', 'patient_id'],
        alias='appointment',
        incremental_strategy='merge',
        transient=false,
        tags=['stable', 'incremental']
    )
}}

select
    lds_source_record_id,
    id,
    provider_organisation_id,
    publisher_organisation_id,
    patient_id,
    person_id,
    practitioner_in_role_id,
    schedule_id,
    start_date,
    planned_duration_mins,
    actual_duration_mins,
    status_source_concept_id,
    appointment_status_source_code,
    appointment_status_source_display,
    appointment_status_code,
    appointment_status_display,
    patient_wait_mins,
    patient_delay_mins,
    datetime_booked,
    datetime_sent_in,
    datetime_left,
    cancelled_date,
    appointment_type,
    age_at_event,
    age_at_event_baby,
    age_at_event_neonate,
    booking_method_source_concept_id,
    booking_method_source_code,
    booking_method_source_display,
    booking_method_code,
    booking_method_display,
    contact_mode_source_concept_id,
    contact_mode_source_code,
    contact_mode_source_display,
    contact_mode_code,
    contact_mode_display,
    is_blocked,
    national_slot_category_name,
    context_type,
    service_setting,
    national_slot_category_description,
    csds_care_contact_identifier,
    publisher_organisation_code,
    patient_shard_id,
    person_shard_id,
    lds_source_record_shard_id,
    lds_id,
    lds_business_key,
    lds_source_dataset_id,
    lds_cdm_event_id,
    lds_versioner_event_id,
    lds_datetime_first_acquired,
    lds_datetime_update_acquired,
    lds_is_deleted,
    lds_start_datetime,
    lds_lakehouse_date_processed,
    lds_lakehouse_datetime_updated
from {{ ref('base_olids_appointment') }}

{% if is_incremental() %}
    where lds_start_datetime > (select max(lds_start_datetime) from {{ this }})
{% endif %}
