{{
    config(
        cluster_by=['id'],
        transient=false,
        alias='patient'
    )
}}

SELECT
    id,
    lds_source_record_id,
    person_id,
    publisher_organisation_id,
    provider_organisation_id,
    author_organisation_id,
    registered_practice_organisation_id,
    local_patient_id,
    sk_patient_id,
    pds_trace_status,
    sk_linkage_status,
    title,
    gender_source_concept_id,
    gender_source_code,
    gender_source_display,
    gender_code,
    gender_display,
    birth_date,
    birth_year,
    birth_month,
    birth_week_iso,
    birth_day,
    death_date,
    death_year,
    death_month,
    death_week_iso,
    is_confidential,
    is_test_patient,
    is_spine_sensitive,
    lds_source_dataset,
    lds_is_deleted,
    publisher_organisation_code,
    clinical_system,
    source_extraction_date,
    lds_transform_datetime
FROM {{ ref('conformed_patient') }}
